#!/bin/bash

# Updates adblocker hosts list.
# Note - hosts.core is what would normally be a hosts file.

mkdir /tmp/adblock
cd /tmp/adblock

# MVPS List
aria2c http://winhelp2002.mvps.org/hosts.txt
mv hosts.txt mvps

cp /etc/hosts.core /etc/hosts

cat mvps >> /etc/hosts

rm -rf /tmp/adblock

sed -i 's/0.0.0.0/127.0.0.1/g' /etc/hosts
