#!/bin/bash

# Used as a cron job to update flashplayer for freshplayer.
# Doing this manually is a chore, so I just do it automatically.
# In good news, this update mechanism shares zero data with adobe. ;P

cd /tmp

mkdir flash
cd flash

aria2c https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
R=$?
if [ ! $R == 0 ]; then
    cd ..
    rm -rf flash
    exit 1
fi
ar vx google-chrome-stable_current_amd64.deb
tar -xvpf data.tar.xz
mkdir -p /usr/lib/chromium-browser/PepperFlash
cp ./opt/google/chrome/PepperFlash/* /usr/lib/chromium-browser/PepperFlash/
chmod 644 /usr/lib/chromium-browser/PepperFlash/*

cd ..
rm -rf flash
